set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'rking/ag.vim'
Plugin 'casperin/vim-plus'

" Syntax and indentation
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'groenewege/vim-less'
Plugin 'elzr/vim-json'
Plugin 'wavded/vim-stylus'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on

if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif
set t_Co=256
